# Generated by Django 3.1.3 on 2020-12-03 04:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='albums title', max_length=100)),
                ('artist', models.CharField(help_text='albums artist', max_length=70)),
                ('genre', models.CharField(help_text='albums genre', max_length=20)),
                ('ryear', models.DateField(help_text='release data')),
                ('image', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='song title', max_length=100)),
                ('artist', models.CharField(help_text='song artist', max_length=70)),
                ('genre', models.CharField(help_text='song genre', max_length=20)),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['mp3', 'mp4', 'aac'])])),
                ('al_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.album')),
            ],
        ),
    ]
